In [1]:
import numpy as np

In [2]:
arreglo_0_a_90_grados = np.array([0, 30, 45, 60, 75, 90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 75, 90])

In [3]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.30899694,
       1.57079633])

In [4]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 0.96592583,
       1.        ])

In [5]:
np.sin(arreglo_0_a_90_grados)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062, -0.38778164,
        0.89399666])

In [8]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       2.58819045e-01, 6.12323400e-17])

In [7]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       3.73205081e+00, 1.63312394e+16])

In [12]:
numero_random = np.random.randint(10)
numero_random

0

In [15]:
numero_random = np.random.randint(-2, 1)  # Los numeros que puden salir son -2,-1,0,1
numero_random

-2

In [21]:
arreglo_random = np.random.randint(-2, 10, 3)
arreglo_random

array([8, 6, 1])

In [22]:
print(np.median(arreglo_random))
print(np.std(arreglo_random))
print(np.var(arreglo_random))
print(np.mean(arreglo_random))

6.0
2.943920288775949
8.666666666666666
5.0
