In [1]:
import numpy as np

In [3]:
arreglo_cero_diez = np.arange(11)
arreglo_cero_diez

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
cuadrados_cero_diez = arreglo_cero_diez ** 2
cuadrados_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
cuadrados_cero_diez[5]

25

In [8]:
cuadrados_cero_diez[0:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [11]:
cuadrados_cero_diez[-1]

100

In [10]:
cuadrados_cero_diez[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [12]:
cuadrados_cero_diez[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
cuadrados_cero_diez[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [14]:
cuadrados_cero_diez[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [21]:
# Otener los elementos pares del arreglo del final al inicio
cuadrados_cero_diez[::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)