In [1]:
# pip install numpy 
import numpy as np

In [5]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
np.zeros((5, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.zeros([1])

array([0.])

In [11]:
np.ones((5, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(-2,10)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [24]:
np.arange(-12, 0.5, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ])

In [28]:
arreglo_pares = np.arange(0, 20, 2)
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2, 3, 4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [29]:
arreglo_pares.reshape((2, 5))
arreglo_pares.reshape((5, 2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [33]:
# Crear un arreglo de 24 elementos y poner todas las posibles combinaciones de elementos
arreglo24 = np.arange(24)
print(arreglo24)
print(arreglo24.reshape((2,2,2,3)))
print(arreglo24.reshape((2,3,2,2)))
print(arreglo24.reshape((2,2,3,2)))
print(arreglo24.reshape((3,2,2,3)))
print(arreglo24.reshape((4,2,3)))
print(arreglo24.reshape((4,3,2)))
print(arreglo24.reshape((3,4,2)))
print(arreglo24.reshape((3,2,4)))
print(arreglo24.reshape((2,3,4)))
print(arreglo24.reshape((2,4,3)))
print(arreglo24.reshape((2,12)))
print(arreglo24.reshape((3,8)))
print(arreglo24.reshape((4,6)))
print(arreglo24.reshape((6,4)))
print(arreglo24.reshape((8,3)))
print(arreglo24.reshape((12,2)))
print(arreglo24.reshape((24,1)))
print(arreglo24.reshape((1,24)))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [34]:
a = np.array([10, 10, 10])
b = np.array([5, 5, 5])
a + b

array([15, 15, 15])

In [35]:
a - b

array([5, 5, 5])

In [36]:
a * b

array([50, 50, 50])

In [57]:
a % b

array([0, 0, 0], dtype=int32)

In [44]:
# crear un arreglo de 3 dimensiones y ejecutar las operaciones básicas
arreglo = np.arange(-1, 1, 0.1)
arreglo.size
arreglo_cambiado = arreglo.reshape(2, 5, 2)
arreglo_cambiado

array([[[-1.00000000e+00, -9.00000000e-01],
        [-8.00000000e-01, -7.00000000e-01],
        [-6.00000000e-01, -5.00000000e-01],
        [-4.00000000e-01, -3.00000000e-01],
        [-2.00000000e-01, -1.00000000e-01]],

       [[-2.22044605e-16,  1.00000000e-01],
        [ 2.00000000e-01,  3.00000000e-01],
        [ 4.00000000e-01,  5.00000000e-01],
        [ 6.00000000e-01,  7.00000000e-01],
        [ 8.00000000e-01,  9.00000000e-01]]])

In [45]:
arreglo_cambiado + 1

array([[[0. , 0.1],
        [0.2, 0.3],
        [0.4, 0.5],
        [0.6, 0.7],
        [0.8, 0.9]],

       [[1. , 1.1],
        [1.2, 1.3],
        [1.4, 1.5],
        [1.6, 1.7],
        [1.8, 1.9]]])

In [49]:
arreglo_cambiado + arreglo_cambiado

array([[[-2.0000000e+00, -1.8000000e+00],
        [-1.6000000e+00, -1.4000000e+00],
        [-1.2000000e+00, -1.0000000e+00],
        [-8.0000000e-01, -6.0000000e-01],
        [-4.0000000e-01, -2.0000000e-01]],

       [[-4.4408921e-16,  2.0000000e-01],
        [ 4.0000000e-01,  6.0000000e-01],
        [ 8.0000000e-01,  1.0000000e+00],
        [ 1.2000000e+00,  1.4000000e+00],
        [ 1.6000000e+00,  1.8000000e+00]]])

In [50]:
arreglo_cambiado - arreglo_cambiado

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
arreglo_cambiado * arreglo_cambiado

array([[[1.00000000e+00, 8.10000000e-01],
        [6.40000000e-01, 4.90000000e-01],
        [3.60000000e-01, 2.50000000e-01],
        [1.60000000e-01, 9.00000000e-02],
        [4.00000000e-02, 1.00000000e-02]],

       [[4.93038066e-32, 1.00000000e-02],
        [4.00000000e-02, 9.00000000e-02],
        [1.60000000e-01, 2.50000000e-01],
        [3.60000000e-01, 4.90000000e-01],
        [6.40000000e-01, 8.10000000e-01]]])

In [52]:
arreglo_cambiado / arreglo_cambiado

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [53]:
arreglo_cambiado % arreglo_cambiado

array([[[-0., -0.],
        [-0., -0.],
        [-0., -0.],
        [-0., -0.],
        [-0., -0.]],

       [[-0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [54]:
arreglo_cambiado % 2

array([[[1. , 1.1],
        [1.2, 1.3],
        [1.4, 1.5],
        [1.6, 1.7],
        [1.8, 1.9]],

       [[2. , 0.1],
        [0.2, 0.3],
        [0.4, 0.5],
        [0.6, 0.7],
        [0.8, 0.9]]])

In [55]:
arreglo2 = np.arange(0, 10, 0.5).reshape(2, 5, 2)
arreglo_cambiado * arreglo2

array([[[-0.00000000e+00, -4.50000000e-01],
        [-8.00000000e-01, -1.05000000e+00],
        [-1.20000000e+00, -1.25000000e+00],
        [-1.20000000e+00, -1.05000000e+00],
        [-8.00000000e-01, -4.50000000e-01]],

       [[-1.11022302e-15,  5.50000000e-01],
        [ 1.20000000e+00,  1.95000000e+00],
        [ 2.80000000e+00,  3.75000000e+00],
        [ 4.80000000e+00,  5.95000000e+00],
        [ 7.20000000e+00,  8.55000000e+00]]])

In [56]:
arreglo_cambiado % arreglo2

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in remainder
  """Entry point for launching an IPython kernel.


array([[[nan, 0.1],
        [0.2, 0.8],
        [1.4, 2. ],
        [2.6, 3.2],
        [3.8, 4.4]],

       [[5. , 0.1],
        [0.2, 0.3],
        [0.4, 0.5],
        [0.6, 0.7],
        [0.8, 0.9]]])

In [58]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a % 2)

[12 12 12]
[8 8 8]
[20 20 20]
[5. 5. 5.]
[0 0 0]


In [88]:
# los mayores a 5 y menores a 12
arreglo_muestra = np.arange(20).reshape(5, 2, 2)
resp1 = arreglo_muestra[arreglo_muestra >6]
print(resp1)
resp2 = arreglo_muestra[arreglo_muestra >6][arreglo_muestra[arreglo_muestra >6] < 14]
print(resp2)
resp3 = arreglo_muestra[arreglo_muestra >6][arreglo_muestra[arreglo_muestra >6] < 14][arreglo_muestra[arreglo_muestra >6][arreglo_muestra[arreglo_muestra >6] < 14]%2 == 0]
print(resp3)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 7  8  9 10 11 12 13]
[ 8 10 12]


In [90]:
resp = arreglo_muestra[arreglo_muestra >6][arreglo_muestra[arreglo_muestra >6] < 14][arreglo_muestra[arreglo_muestra >6][arreglo_muestra[arreglo_muestra >6] < 14]%2 == 0]
print(resp)

[ 8 10 12]


In [92]:
# solucion 1
mayor_cinco = arreglo_muestra > 5
menor_doce = arreglo_muestra < 12
mod_dos = arreglo_muestra % 2 == 0
resp = arreglo_muestra[mayor_cinco & menor_doce & mod_dos]
print(resp)

[ 6  8 10]


In [94]:
# solucion 2
mayor_cinco = arreglo_muestra > 5
menor_doce = arreglo_muestra < 12
mod_dos = arreglo_muestra % 2 == 0
resp = arreglo_muestra[mayor_cinco * menor_doce * mod_dos]
print(resp)

[ 6  8 10]


In [98]:
A = np.arange(4).reshape((2, 2))
A

array([[0, 1],
       [2, 3]])

In [97]:
B = np.arange(5, 9).reshape((2, 2))
B

array([[5, 6],
       [7, 8]])

In [99]:
A.dot(B)

array([[ 7,  8],
       [31, 36]])

In [100]:
np.dot(A, B)

array([[ 7,  8],
       [31, 36]])

In [101]:
B.dot(A)

array([[12, 23],
       [16, 31]])

In [102]:
np.dot(B, A)

array([[12, 23],
       [16, 31]])

In [103]:
arreglo_doce = np.arange(12)
print(arreglo_doce.sum())
print(arreglo_doce.max())
print(arreglo_doce.min())

66
11
0


In [109]:
arreglo_doce = np.arange(12).reshape(3, 2, 2)
print(arreglo_doce.sum())
print(arreglo_doce.max())
print(arreglo_doce.min())

66
11
0


In [113]:
print(arreglo_doce)  # 3, 2, 2
print('*******')
print(arreglo_doce.sum(axis = 0))
print('*******')
print(arreglo_doce.sum(axis = 1))
print('*******')
print(arreglo_doce.sum(axis = 2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
*******
[[12 15]
 [18 21]]
*******
[[ 2  4]
 [10 12]
 [18 20]]
*******
[[ 1  5]
 [ 9 13]
 [17 21]]


In [115]:
arreglo_doce = np.arange(24).reshape(3, 2, 2, 2)
print(arreglo_doce)
print('*******')
print(arreglo_doce.sum(axis = 0))
print('*******')
print(arreglo_doce.sum(axis = 1))
print('*******')
print(arreglo_doce.sum(axis = 2))
print('*******')
print(arreglo_doce.sum(axis = 3))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
*******
[[[24 27]
  [30 33]]

 [[36 39]
  [42 45]]]
*******
[[[ 4  6]
  [ 8 10]]

 [[20 22]
  [24 26]]

 [[36 38]
  [40 42]]]
*******
[[[ 2  4]
  [10 12]]

 [[18 20]
  [26 28]]

 [[34 36]
  [42 44]]]
*******
[[[ 1  5]
  [ 9 13]]

 [[17 21]
  [25 29]]

 [[33 37]
  [41 45]]]
